---
fixtures:
  repositories:
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd: https://github.com/simp/puppet-systemd
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
  symlinks:
    selinux: "#{source_dir}"
