---
fixtures:
  repositories:
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    compliance_markup:
      repo: "https://github.com/simp/pupmod-simp-compliance_markup"
      branch: "testing_hotfix_06062019"
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
  symlinks:
    selinux: "#{source_dir}"
