---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub.git
    selinux_core: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux.git
      branch: simp-master
  symlinks:
    selinux: "#{source_dir}"
