---
HOSTS:
  centos10:
    roles:
    - server
    platform: el-10-x86_64
    box: centos/stream10
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      chef-current:
        baseurl: https://packages.chef.io/repos/yum/current/el/9/$basearch
        gpgkeys:
        - https://packages.chef.io/chef.asc
    family: centos-cloud/centos-stream-10
    gce_machine_type: n1-standard-2
  centos9:
    roles:
    - server
    - master
    platform: el-9-x86_64
    box: generic/centos9s
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      chef-current:
        baseurl: https://packages.chef.io/repos/yum/current/el/9/$basearch
        gpgkeys:
        - https://packages.chef.io/chef.asc
    family: centos-cloud/centos-stream-9
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  puppet_collection: <%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'openvox8') %>
